name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        node-version: [14, 16, 18]

    name: Test for node-${{ matrix.node-version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Send coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
